package StudyJava;

public class Exceptionclass {

	public static void main(String[] args) {
		/*
		 * try { 
		 * while(true) { if() // 첫번째 에러발생 시킴 >>>> 두번째 에러문까지 가는게 아니라 바로 catch문으로 가서 해당 에러문에 대해서 검사
		 * while(true) { if() // 두번째 에러발생 시킴}
		 *  }catch (첫번째 exception e) {
		 * System.out.println("this is first error"); 
		 * }catch (두번째 exception e) {
		 * System.out.println("this is second error");
		 *  }catch (마지막 exception ==> Exception e (예외의 조상) 을 써줌으로서 앞에서 못잡았던 오류를 잡아줌)  { } 
		 *  finally { System.out.println("good"); } 
		 *  첫번째 에러만 읽고 finally로 넘어와서 출력하고 끝냄
		 *  두번째 에러문을 잡고싶으면 첫번째 해결하고 다시 돌려줘야함 ㅋㅋ;
		 */	
		}

}
